from pathlib import Path
import re, sys
ROOT = Path(__file__).resolve().parents[1]
errors=[]; passed=[]
def check(name, cond):
    (passed if cond else errors).append(name)

def text(rel): return (ROOT/rel).read_text(encoding='utf-8')

all_cs=list(ROOT.rglob('*.cs'))
check('C# files present', bool(all_cs))
check('all C# brace counts balanced (coarse)', all(s.read_text(encoding='utf-8').count('{') == s.read_text(encoding='utf-8').count('}') for s in all_cs))
sort=text('HealthAutoArrange.Core/SortPlan.cs')
check('stable tie-break uses original StateIndex', 'a.StateIndex.CompareTo(b.StateIndex)' in sort)
parser=text('HealthAutoArrange.Core/ConfigTextParser.cs')
check('unknown default is Keep', 'var policy = UnknownStatePolicy.Keep;' in parser)
plugin=text('HealthAutoArrange.Plugin/Plugin.cs')
check('refresh hook has Update/AddAll fallback', '"UpdateMoodles"' in plugin and '"AddAllMoodles"' in plugin and '??' in plugin)
check('state catalog uses observed UI nodes', 'Adapter?.RefreshObservedStates()' in plugin)
adapter=text('HealthAutoArrange.Plugin/UnityUiAdapter.cs')
check('adapter records real-node observations', '_observations.Observe(' in adapter and 'RefreshObservedStates' in adapter)
window=text('HealthAutoArrange.Plugin/FallbackSettingsWindow.cs')
check('GUI uses hover info content', 'new GUIContent("i", help' in window and 'GUI.tooltip' in window)
check('advanced/reminders are collapsed sections', '_showAdvanced' in window and '_showReminders' in window)
check('GUI visibly tracks unsaved reminder edits', 'ReminderFingerprint' in window and '_text.Unsaved' in window)
check('state selection no longer autosaves to disk', 'private void SaveSelection' not in window)
editor=text('HealthAutoArrange.Core/GroupSelectionEditor.cs')
check('empty groups are preserved for first assignment', 'EnsureGroup' in editor)
rules=text('HealthAutoArrange.Core/RulesFileStore.cs')
check('rules writer does not delete destination before replacement', 'File.Delete(path)' not in rules and 'File.Replace' in rules)
csproj=text('HealthAutoArrange.Plugin/HealthAutoArrange.Plugin.csproj')
check('game path is configurable', 'HEALTHAUTOARRANGE_GAME_DIR' in csproj and 'HealthAutoArrange.Local.props' in csproj)
check('no fake medical starter mapping', 'Group.Vital.States' not in plugin and 'Reminder.Bleeding' not in plugin)

identity=text('HealthAutoArrange.Core/MoodleIdentity.cs')
selection=text('HealthAutoArrange.Core/SelectionResultGenerator.cs')
check('generated severity-family pattern preserves semantic trailing digits', 'PatternBaseId' in identity and 'NormalizeRuntimeId(state)' in selection and 'baseId + "#"' in selection)
check('observed catalog is bounded', 'MaxStates = 256' in text('HealthAutoArrange.Core/StateObservationRegistry.cs'))
check('missing-capture observation preserves exact runtime ID', ': normalizedRuntime;' in text('HealthAutoArrange.Core/StateObservationRegistry.cs') and 'BaseId + "#"' in text('HealthAutoArrange.Core/StateObservationRegistry.cs'))
check('provisional observation merges when reliable capture arrives', 'state.MergeFrom(provisional)' in text('HealthAutoArrange.Core/StateObservationRegistry.cs'))

capture=text('HealthAutoArrange.Core/MoodleCapture.cs')
check('capture resolution can be scoped to current manager', 'ReferenceEquals(item.Manager, manager)' in capture)
check('capture fallback preserves semantic numeric icon IDs', 'MatchesSeverityFamily(iconId, normalized)' in capture and 'MoodleIdentity.BaseId(item.IconId) == baseId' not in capture)
check('anchored auto mode requires horizontal row slots', 'hasDistinctHorizontalSlots' in adapter and 'OriginalAnchoredPosition.x' in adapter)

# v1.1.3 reminder safety / migration / localization contracts
repeat=text('HealthAutoArrange.Core/ReminderRepeatMode.cs')
rule=text('HealthAutoArrange.Core/ReminderRule.cs')
engine=text('HealthAutoArrange.Core/ReminderEngine.cs')
presentation=text('HealthAutoArrange.Core/ReminderPresentation.cs')
dispatcher=text('HealthAutoArrange.Plugin/ReminderDispatcher.cs')
ui=text('HealthAutoArrange.Core/UiConfigModel.cs')
check('plugin version is 1.1.3', '"1.1.3"' in plugin and 'AssemblyVersion("1.1.3.0")' in text('HealthAutoArrange.Plugin/Properties/AssemblyInfo.cs'))
check('reminder supports once and while-present modes', 'Once = 0' in repeat and 'WhilePresent = 1' in repeat)
check('legacy zero cooldown migrates to once', 'CooldownSeconds=0 migrated to RepeatMode=Once' in parser and 'cooldownSeconds > 0d ? ReminderRepeatMode.WhilePresent : ReminderRepeatMode.Once' in rule)
check('repeat interval is period divided by count', 'PeriodSeconds / SendsPerPeriod' in rule)
check('engine resets episode after disappearance', 'rt.ResetEpisode()' in engine and 'WasPresent = false' in engine)
check('reminder episode has transient UI absence grace', 'EpisodeResetGraceSeconds = 1d' in engine and 'AbsentSince' in engine)
check('engine does not burst catch up missed repeat slots', 'rt.NextDueAt = now.AddSeconds(rule.EffectiveIntervalSeconds)' in engine and 'while (now >=' not in engine)
check('reminder cadence has timer tick independent of Moodle refresh', 'ReminderTickSeconds = 0.25f' in adapter and 'RunRemindersSnapshot()' in adapter)
check('reminders do not emit from refresh processing while game is paused', 'if (Time.timeScale > 0f)' in adapter and 'RunRemindersSnapshot();' in adapter)
check('sorting toggle no longer disables reminder observation/ticks', 'if (!_runtime.Enabled) return;' not in adapter.split('public void Update()',1)[1].split('private void ProcessRefresh()',1)[0] and 'if (!_runtime.Enabled || visuals.Count < 2) return;' in adapter)
check('reconfigure preserves continuous reminder episode state', '_reminders.Reconfigure(config.Reminders)' in adapter and 'new ReminderEngine(config.Reminders)' not in adapter)
check('timer reminder uses cached UI-confirmed visual snapshot', '_lastVisualSnapshot' in adapter and 'BuildContext(message, _lastVisualSnapshot)' in adapter)
check('BottomAlert avoids native DoAlert double delivery', 'case ReminderMode.BottomAlert:' in dispatcher and 'PlayerCamera.main' not in dispatcher)
check('Log mode stays non-visual', 'message.Mode != ReminderMode.BottomAlert' in plugin)
check('presentation replaces same-state active visual instead of stacking', '_items.RemoveAll(i => string.Equals(i.BaseState, baseState' in presentation)
check('presentation dedupe preserves semantic trailing digits in generated/legacy patterns', 'MoodleIdentity.PatternBaseId(state)' in presentation)
check('GUI exposes repeat mode plus period and sends fields', 'DrawReminderFrequency(rule' in window and 'text.SendsPerPeriod' in window and 'GUILayout.SelectionGrid' in window)
check('new rules serialize repeat fields instead of legacy cooldown', '.RepeatMode = ' in ui and '.PeriodSeconds = ' in ui and '.SendsPerPeriod = ' in ui)
check('legacy cooldown remains readable for migration', 'legacyCooldownSuffix = ".CooldownSeconds"' in parser)
check('invariant numeric parsing used for reminder period', 'CultureInfo.InvariantCulture' in parser and 'TryParseInvariantDouble' in parser)
check('repeat frequency is capped to a deliverable one-second minimum interval', 'MinimumEffectiveIntervalSeconds = 1d' in rule and 'NormalizeSends(double periodSeconds' in rule)
check('repeat period has a finite upper bound', 'MaximumPeriodSeconds = 604800d' in rule and 'Math.Min(MaximumPeriodSeconds, value)' in rule)
check('partial legacy/new frequency migration is field-aware', 'HasRepeatModeField' in parser and 'HasPeriodField' in parser and 'HasSendsField' in parser)
check('duplicate reminder names cannot share runtime episode state', '_runtime = _rules.Select(_ => new RuleRuntimeState()).ToList()' in engine)

# v1.1.3 localization / stale metadata / numeric robustness
textcat=text('HealthAutoArrange.Core/UiTextCatalog.cs')
overlay=text('HealthAutoArrange.Plugin/TransparentReminderOverlay.cs')
numeric=text('HealthAutoArrange.Core/NumericSafety.cs')
check('GUI has explicit Chinese-English switch button', 'LanguageButton' in window and 'SetLanguage(!_text.IsChinese)' in window and 'IFallbackSettingsLanguageActions' in window)
check('GUI language persists independently of game language', 'Config.Bind("UI", "Language", "Auto"' in plugin and '_uiLanguage.Value = chinese ? "Chinese" : "English"' in plugin)
check('overlay follows GUI language switch', '_overlay?.SetLanguage(chinese)' in plugin and 'public void SetLanguage(bool chinese)' in overlay)
check('hardcoded GUI helper strings moved into text catalog', 'UnknownMovedNote' in textcat and 'SelectState' in textcat and 'UseLog' in textcat and 'CatalogRefreshFailed' in textcat)
check('capture metadata is bounded by refresh sequence', 'LatestSequence' in capture and 'minSequenceExclusive' in capture and '_captureBoundaryByManager' in adapter)
check('capture refresh window is manager scoped', 'manager.GetInstanceID()' in adapter and '_captureBoundaryByManager.TryGetValue' in adapter)
matcher=text('HealthAutoArrange.Core/StateMatcher.cs')
check('GUI severity-family pattern only accepts numeric suffixes', 'pattern.EndsWith("#"' in matcher and '!char.IsDigit(suffix[i])' in matcher)
check('legacy broad star wildcard remains supported', 'pattern.EndsWith("*"' in matcher)
check('non-finite visual inputs are rejected', 'ClampFinite' in numeric and 'NumericSafety.IsFinite(parsed)' in window and 'NumericSafety.IsFinite(result)' in parser)
check('narrow reminder layout splits long English numeric controls', 'if (narrow)' in window and 'DrawLabeledFloat' in window and 'GUILayout.Label(text.SendsPerPeriod, GUILayout.Width(narrow ? 150f : 132f))' in window)

print('HealthAutoArrange static smoke')
for p in passed: print('[PASS]', p)
for e in errors: print('[FAIL]', e)
print(f'Passed {len(passed)}/{len(passed)+len(errors)}')
sys.exit(1 if errors else 0)
